### ISSUE TITLE
"WARNING    gmusic/all_access unknown config key"

### ISSUE THREAD

**Issue by danielmaxsteel** [hechtus/mopidy-gmusic#73]
Badly I'm not able to get to work the all_access function. I'm getting the warning:
"WARNING    gmusic/all_access unknown config key."

My "/etc/mopidy/mopidy.conf"-file looks like this:

[gmusic]
username = daniel********
password = ********
deviceid = 315*******
all_access = true

Am I'm doing something wrong, or is it a known problem? (PS: I have a german google all access account)

**Comment by drampelt** [comment]
See #58

**Comment by afterthought325** [comment]
I'm getting this error as well, even after following the instructions from #58
